version: '3.8'
services:
  node-dev:
    build:
      context: .
      args:
        - NODE_VER=18.16
    volumes:
      - node_modules:/workspaces/node_modules
      - pnpm-store:/workspaces/.pnpm-store
      - .:/workspaces
    environment:
      - TZ=Asia/Tokyo
volumes:
  node_modules:
  pnpm-store:
