version: '3.8'
services:
  node-dev:
    build:
      context: .
      args:
        - NODE_VER=18.16
    volumes:
      - workspaces:/workspaces
    environment:
      - TZ=Asia/Tokyo
volumes:
  workspaces:
